export const EXAMPLE_PATH = 'blog-starter'
export const CMS_NAME = 'Markdown'
export const HOME_OG_IMAGE_URL =
  'https://og-image.vercel.app/Next.js%20Blog%20Starter%20Example.png?theme=light&md=1&fontSize=100px&images=https%3A%2F%2Fassets.vercel.com%2Fimage%2Fupload%2Ffront%2Fassets%2Fdesign%2Fnextjs-black-logo.svg'
export const BLOG_NAME = 'Andy Delso'
export const KEYWORDS = 'android, kotlin, qa, testing, automation, next.js'
export const DESCRIPTION = 'A personal site and blog'
export const AUTHOR = 'andy delso'
export const LANG = 'en-US'
export const GITHUB_REPO = 'https://github.com/ddaypunk'
